# Generated by Django 4.2.5 on 2023-09-14 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_plant_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fed', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default=('N', 'No'), max_length=1)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.plant')),
            ],
        ),
    ]
