# Generated by Django 4.2.5 on 2023-09-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_watered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watered',
            name='fed',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=1),
        ),
    ]
