# Generated by Django 4.2.5 on 2023-09-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_watered_fed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watered',
            name='fed',
            field=models.CharField(choices=[('N', 'and not fed'), ('Y', 'and fed')], default='N', max_length=1),
        ),
    ]
