# Generated by Django 4.2.5 on 2023-09-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_watered_fed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watered',
            name='date',
            field=models.DateField(verbose_name='watered date'),
        ),
        migrations.AlterField(
            model_name='watered',
            name='fed',
            field=models.CharField(choices=[('N', 'watered and not fed on'), ('Y', 'watered and fed on')], default='N', max_length=1),
        ),
    ]
