# Generated by Django 4.2.5 on 2023-09-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_watered_date_alter_watered_fed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
