# Generated by Django 4.2.5 on 2023-09-25 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_name_plant_common_name_plant_family_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watered',
            options={'ordering': ['-date']},
        ),
    ]
