# Generated by Django 4.2.5 on 2023-09-27 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_watered_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel', models.CharField(max_length=20)),
                ('medium', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Status Date')),
                ('no_of_leaves', models.IntegerField()),
                ('state', models.CharField(choices=[('A', 'Actively Growing'), ('D', 'Dormant'), ('R', 'Rehabbing: Health Declining.')], default='A', max_length=1)),
                ('status_log', models.CharField(max_length=1000)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.plant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='pots',
            field=models.ManyToManyField(to='main_app.pot'),
        ),
    ]
