# Generated by Django 4.2.5 on 2023-09-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_pot_status_plant_pots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pot',
            name='medium',
            field=models.CharField(max_length=200),
        ),
    ]
